# Generated by Django 4.2.7 on 2023-11-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.DateField(auto_now_add=True, verbose_name='최근 질문 날짜')),
                ('today_quiz', models.PositiveSmallIntegerField(default=5, verbose_name='질문한 횟수')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 아이디')),
            ],
        ),
    ]
